version: "3.8"
services:
  trading_app:
    container_name: trading_app
    image: trading_app
    build: .
    volumes:
      - ./:/app
    ports:
      - "8012:8000"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - trading_app_db

  trading_app_db:
    image: postgres:14.6-alpine
    container_name: trading_app_db
    hostname: trading_app_db
    ports:
      - 5423:5432
    volumes:
      - ../trading_app_db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
