version: "3.8"
services:
  trading_app:
    container_name: trading_app
    image: trading_app
    build: .
    volumes:
      - ./:/app
    ports:
      - "8012:8000"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - trading_app_db

  trading_app_db:
    image: postgres:14.6-alpine
    container_name: trading_app_db
    hostname: trading_app_db
    ports:
      - 5423:5432
    volumes:
      - ../trading_app_db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}

  redis:
    image: redis:7.0-alpine
    container_name: trading-redis
    hostname: redis

  trading_worker:
    container_name: trading_worker
    image: trading_worker
    build: .
    hostname: worker
    volumes:
      - ./:/app
    command: celery -A src.tasks.tasks:celery worker --loglevel=INFO --pool=solo
    links:
      - redis
    depends_on:
      - trading_app_db
      - redis

  trading_flower:
    container_name: trading_flower
    image: trading_flower
    build: .
    hostname: flower
    volumes:
      - ./:/app
    ports:
      - "5555:5555"
    command: celery -A src.tasks.tasks:celery flower
    links:
      - redis
    depends_on:
      - trading_app_db
      - redis
